version: 2
jobs:
  test_model_py37:
    working_directory: ~/project/
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/housing_model/requirements.txt
            pip install -e packages/housing_model
            py.test -vv packages/housing_model/housingmodel/tests

  train_and_upload_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r packages/housing_model/requirements.txt
            pip install -e packages/housing_model
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            PYTHONPATH=./packages/housing_model
            python3 packages/housing_model/housingmodel/train_pipeline.py
            ./scripts/publish_model.sh ./packages/housing_model/

  test_ml_api_py37:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/housing_api/requirements.txt
            py.test -vv packages/housing_api/housing_api/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_model_py37
      - train_and_upload_model
      - test_ml_api_py37
      - test_ml_api_py37:
          requires:
            - train_and_upload_model
