version: 2
jobs:
  test_model_py37:
    working_directory: ~/project/
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/housing_model/requirements.txt
            py.test -vv packages/housing_model/housingmodel/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_model_py37
